<div style="background-color:#f3e5f5; color:black; padding:20px; border-radius:15px; border: 1px solid #ccc; box-shadow: 0 2px 4px rgba(0,0,0,0.1);text-align:center">
  <h2 style="margin-top: 0;text-align:center">Exercises 03</h2>
  <p style="font-size:16px;text-align:center">Numpy, Pandas, OOP</p><br>
    3350
</div>

<div style="background-color:#f3e5f5; color:black; padding:20px; border-radius:15px; border: 1px solid #ccc; box-shadow: 0 2px 4px rgba(0,0,0,0.1);">
  <h2 style="margin-top: 0;">Exercises 01</h2>
Create an 3d numpy array with dimensions (4, 5, 3), and print the dimensions finally.
</div>

In [1]:
import numpy as np

In [2]:
np.empty((4, 5, 3))

array([[[ 1.34465544e-311,  1.34463585e-311, -1.22181971e+083],
        [ 4.84314707e+149,  7.91592928e-304, -5.34265478e+236],
        [-2.64038989e+232,  6.55670584e-293,  1.08468090e-202],
        [ 7.71848920e-304, -7.23926730e+077,  4.47824803e-087],
        [ 1.93319869e-130,  8.19927652e-121, -3.31161430e+097]],

       [[-1.63049343e+232,  1.16538919e-163,  5.05838908e-299],
        [-8.54037751e+231,  8.20418168e-304,  6.00935416e-300],
        [-2.77754119e+097,  8.59847849e-174,  8.59847843e-174],
        [ 3.67048536e-304,  3.13197199e-292, -2.88441689e+097],
        [ 8.59847849e-174,  6.55014888e-165,  3.67760558e-304]],

       [[ 2.92496572e-135,  5.05845288e-299, -7.23926733e+077],
        [ 2.42765481e-106,  7.96756490e-304,  2.42874854e+289],
        [ 1.63342494e-301,  7.96755099e-304,  1.39311500e+005],
        [ 7.52882399e-300,  1.23977720e-302,  3.66514515e-304],
        [ 1.08468090e-202,  4.88030505e-193,  7.53173940e-300]],

       [[ 3.69629662e-304,  4.5242

In [3]:
arr = np.array([
                [
                    [1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9],
                    [10, 11, 12],
                    [13, 14, 15]
                ],
                [
                    [1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9],
                    [10, 11, 12],
                    [13, 14, 15]
                ],
                [
                    [1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9],
                    [10, 11, 12],
                    [13, 14, 15]
                ],
                [
                    [1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9],
                    [10, 11, 12],
                    [13, 14, 15]
                ]
              ])

In [4]:
arr

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15]],

       [[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15]],

       [[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15]],

       [[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12],
        [13, 14, 15]]])

In [5]:
arr.shape

(4, 5, 3)

In [6]:
arr.ndim

3

<div style="background-color:#f3e5f5; color:black; padding:20px; border-radius:15px; border: 1px solid #ccc; box-shadow: 0 2px 4px rgba(0,0,0,0.1);">
  <h2 style="margin-top: 0;">Exercises 02</h2>
change the shape of created array in the exercise 01 to (20, 3) and check the current dimensions! 
</div>

In [8]:
new_arr = arr.reshape(20, 3)

In [9]:
new_arr.shape

(20, 3)

In [10]:
new_arr.ndim

2

In [11]:
arr.reshape(20, 5)

ValueError: cannot reshape array of size 60 into shape (20,5)

<div style="background-color:#f3e5f5; color:black; padding:20px; border-radius:15px; border: 1px solid #ccc; box-shadow: 0 2px 4px rgba(0,0,0,0.1);">
  <h2 style="margin-top: 0;">Exercises 03</h2>
index and print the number 50 from the arr.<br>
arr = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])
</div>

In [12]:
arr2 = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])

arr2

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [13]:
arr2[1, 0]

50

<div style="background-color:#f3e5f5; color:black; padding:20px; border-radius:15px; border: 1px solid #ccc; box-shadow: 0 2px 4px rgba(0,0,0,0.1);">
  <h2 style="margin-top: 0;">Exercises 04</h2>
Change the element datatype of the arr to float!<br>
arr = np.array([[10, 20, 30, 40], [50, 60, 70, 80]])
</div>

In [14]:
arr2

array([[10, 20, 30, 40],
       [50, 60, 70, 80]])

In [17]:
np.float64(arr2)

array([[10., 20., 30., 40.],
       [50., 60., 70., 80.]])

In [19]:
arr2.astype(float)

array([[10., 20., 30., 40.],
       [50., 60., 70., 80.]])

In [21]:
np.array(arr2, dtype = "d")

array([[10., 20., 30., 40.],
       [50., 60., 70., 80.]])

<div style="background-color:#f3e5f5; color:black; padding:20px; border-radius:15px; border: 1px solid #ccc; box-shadow: 0 2px 4px rgba(0,0,0,0.1);">
  <h2 style="margin-top: 0;">Exercises 05</h2>
join arr1 and arr2 into a single array!<br>
arr1 = np.array([1, 2, 3])<br>
arr2 = np.array([4, 5, 6])
<br><br>
</div>

In [22]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([3, 5, 6])

In [23]:
np.concatenate((arr1, arr2))

array([1, 2, 3, 3, 5, 6])

In [24]:
np.hstack((arr1, arr2))

array([1, 2, 3, 3, 5, 6])

In [25]:
np.vstack((arr1, arr2))

array([[1, 2, 3],
       [3, 5, 6]])

<div style="background-color:#f3e5f5; color:black; padding:20px; border-radius:15px; border: 1px solid #ccc; box-shadow: 0 2px 4px rgba(0,0,0,0.1);">
  <h2 style="margin-top: 0;">Exercises 06</h2>
    <p style="font-size:16px;"><b>Pandas</b></p><br>
Load the dataset (cancer.csv)!
</div>

In [26]:
import pandas as pd

In [27]:
df = pd.read_csv("cancer.csv")

In [28]:
df.head()

State  Total.Rate  Total.Number  Total.Population  Rates.Age.< 18  \
0     Alabama       214.2       71529.0        33387205.0             2.0   
1      Alaska       128.1        6361.0         4966180.0             1.7   
2     Arizona       165.6       74286.0        44845598.0             2.5   
3    Arkansas       223.9       45627.0        20382448.0             2.3   
4  California       150.9      393980.0       261135696.0             2.6   

   Rates.Age.18-45  Rates.Age.45-64  Rates.Age.> 64  \
0             18.5            244.7          1017.8   
1             11.8            170.9           965.2   
2             13.6            173.6           840.2   
3             17.6            250.1          1048.3   
4             13.7            163.7           902.4   

   Rates.Age and Sex.< 18.Female  Rates.Age and Sex.< 18.Male  ...  \
0                            2.0                          2.1  ...   
1                            0.0                          0.0  ...   
2                            2.6                          2.5  ...   
3                            2.6                          2.0  ...   
4                            2.4                          2.8  ...   

   Types.Lung.Age and Sex.Male.45 - 64  Types.Lung.Age and Sex.Female.> 64  \
0                                102.9                               221.7   
1                                 50.3                               268.3   
2                                 47.0                               191.9   
3                                106.5                               248.7   
4                                 36.8                               192.5   

   Types.Lung.Age and Sex.Male.> 64  Types.Lung.Race.White  \
0                             457.4                   59.9   
1                             335.0                   48.7   
2                             275.8                   39.5   
3                             484.7                   63.4   
4                             269.0                   37.2   

   Types.Lung.Race.White non-Hispanic  Types.Lung.Race.Black  \
0                                60.4                   52.6   
1                                49.5                   45.6   
2                                42.2                   38.2   
3                                64.2                   62.9   
4                                42.6                   46.5   

   Types.Lung.Race.Black non-Hispanic  Types.Lung.Race.Asian  \
0                                52.8                   23.0   
1                                47.9                   33.0   
2                                40.4                   21.3   
3                                63.0                   18.1   
4                                48.6                   25.8   

   Types.Lung.Race.Indigenous  Types.Lung.Race.Hispanic  
0                        22.9                      14.8  
1                        74.4                       0.0  
2                        11.1                      21.6  
3                        16.2                      14.6  
4                        18.4                      18.3  

[5 rows x 75 columns]

<div style="background-color:#f3e5f5; color:black; padding:20px; border-radius:15px; border: 1px solid #ccc; box-shadow: 0 2px 4px rgba(0,0,0,0.1);">
  <h2 style="margin-top: 0;">Exercises 07</h2>
Print an overview of the dataset.
</div>

In [29]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51 entries, 0 to 50
Data columns (total 75 columns):
 #   Column                                        Non-Null Count  Dtype  
---  ------                                        --------------  -----  
 0   State                                         51 non-null     object 
 1   Total.Rate                                    51 non-null     float64
 2   Total.Number                                  51 non-null     float64
 3   Total.Population                              51 non-null     float64
 4   Rates.Age.< 18                                51 non-null     float64
 5   Rates.Age.18-45                               51 non-null     float64
 6   Rates.Age.45-64                               51 non-null     float64
 7   Rates.Age.> 64                                51 non-null     float64
 8   Rates.Age and Sex.< 18.Female                 51 non-null     float64
 9   Rates.Age and Sex.< 18.Male                   51 non-null     float

<div style="background-color:#f3e5f5; color:black; padding:20px; border-radius:15px; border: 1px solid #ccc; box-shadow: 0 2px 4px rgba(0,0,0,0.1);">
  <h2 style="margin-top: 0;">Exercises 08</h2>
Print 13 last samples of the dataset.
</div>

In [31]:
df.tail(13)

State  Total.Rate  Total.Number  Total.Population  \
38    Pennsylvania       227.7      202230.0        88825682.0   
39    Rhode Island       211.2       15570.0         7371636.0   
40  South Carolina       202.6       65561.0        32366134.0   
41    South Dakota       196.2       11212.0         5714307.0   
42       Tennessee       213.1       94678.0        44430836.0   
43           Texas       145.8      257000.0       176270421.0   
44            Utah        98.5       19022.0        19321462.0   
45         Vermont       211.6        9261.0         4377262.0   
46        Virginia       177.1       99278.0        56054333.0   
47      Washington       175.9       82864.0        47114240.0   
48   West Virginia       254.6       32950.0        12940212.0   
49       Wisconsin       197.5       78578.0        39788899.0   
50         Wyoming       167.9        6603.0         3931624.0   

    Rates.Age.< 18  Rates.Age.18-45  Rates.Age.45-64  Rates.Age.> 64  \
38             2.2             15.7            204.1          1057.3   
39             1.4             13.3            190.3          1052.1   
40             2.1             17.0            235.5           957.1   
41             2.3             12.4            175.7          1007.1   
42             2.4             17.7            245.2          1032.1   
43             2.5             14.7            186.6           904.8   
44             1.9             10.9            132.3           735.8   
45             2.2             16.2            188.1          1002.8   
46             2.2             14.5            189.3           971.0   
47             2.3             13.2            177.5           982.0   
48             2.5             20.3            254.0          1068.9   
49             2.2             13.8            181.2          1028.1   
50             0.0             11.8            168.3           924.9   

    Rates.Age and Sex.< 18.Female  Rates.Age and Sex.< 18.Male  ...  \
38                            2.1                          2.4  ...   
39                            0.0                          0.0  ...   
40                            2.1                          2.2  ...   
41                            0.0                          3.2  ...   
42                            2.3                          2.5  ...   
43                            2.3                          2.7  ...   
44                            1.6                          2.2  ...   
45                            0.0                          0.0  ...   
46                            1.9                          2.5  ...   
47                            2.3                          2.3  ...   
48                            2.2                          2.7  ...   
49                            2.1                          2.2  ...   
50                            0.0                          0.0  ...   

    Types.Lung.Age and Sex.Male.45 - 64  Types.Lung.Age and Sex.Female.> 64  \
38                                 66.5                               225.8   
39                                 64.2                               247.9   
40                                 91.3                               212.9   
41                                 56.4                               206.2   
42                                101.0                               248.4   
43                                 54.3                               200.0   
44                                 26.0                                92.7   
45                                 59.7                               243.6   
46                                 63.4                               226.2   
47                                 49.4                               241.1   
48                                100.2                               264.7   
49                                 55.0                               223.1   
50                                 39.0                  

<div style="background-color:#f3e5f5; color:black; padding:20px; border-radius:15px; border: 1px solid #ccc; box-shadow: 0 2px 4px rgba(0,0,0,0.1);">
  <h2 style="margin-top: 0;">Exercises 09</h2>
Print states with total rate of less than 200
</div>

In [33]:
df[df['Total.Rate']<200]['State']

1                   Alaska
2                  Arizona
4               California
5                 Colorado
6              Connecticut
8     District of Columbia
10                 Georgia
11                  Hawaii
12                   Idaho
13                Illinois
16                  Kansas
20                Maryland
21           Massachusetts
23               Minnesota
26                 Montana
27                Nebraska
28                  Nevada
29           New Hampshire
30              New Jersey
31              New Mexico
32                New York
33          North Carolina
34            North Dakota
37                  Oregon
41            South Dakota
43                   Texas
44                    Utah
46                Virginia
47              Washington
49               Wisconsin
50                 Wyoming
Name: State, dtype: object

<div style="background-color:#f3e5f5; color:black; padding:20px; border-radius:15px; border: 1px solid #ccc; box-shadow: 0 2px 4px rgba(0,0,0,0.1);">
  <h2 style="margin-top: 0;">Exercises 10</h2>
Print number of states with total rate of less than 200
</div>

In [34]:
df[df['Total.Rate']<200]['State'].count()

31

In [36]:
(df['Total.Rate']<200).sum()

31

<div style="background-color:#f3e5f5; color:black; padding:20px; border-radius:15px; border: 1px solid #ccc; box-shadow: 0 2px 4px rgba(0,0,0,0.1);">
  <h2 style="margin-top: 0;">Exercises 11</h2>
Print rows from 35 to the end , and columns between 14 to 28 (use iloc)
</div>

In [37]:
df.iloc[35:, 15:28]

Rates.Age and Sex.> 64.Male  Rates.Race.White  \
35                       1288.3             185.3   
36                       1279.4             190.2   
37                       1169.2             173.7   
38                       1276.5             177.7   
39                       1291.3             176.7   
40                       1195.1             175.1   
41                       1195.0             163.3   
42                       1294.7             189.4   
43                       1104.0             162.5   
44                        884.9             128.9   
45                       1165.8             175.0   
46                       1170.7             168.9   
47                       1142.0             171.3   
48                       1299.9             198.6   
49                       1233.6             169.9   
50                       1064.5             161.5   

    Rates.Race.White non-Hispanic  Rates.Race.Black  Rates.Race.Asian  \
35                          186.0             218.0              98.7   
36                          192.6             222.1             122.1   
37                          175.5             200.8             118.0   
38                          178.2             222.4              96.5   
39                          179.0             128.6             113.2   
40                          176.1             211.2              88.1   
41                          163.8              77.4             149.0   
42                          190.9             231.6              93.5   
43                          172.6             208.6              94.4   
44                          129.7             132.0             105.3   
45                          175.0             130.3             109.2   
46                          170.7             208.0              98.8   
47                          173.5             189.0             120.1   
48                          199.4             216.3              67.1   
49                          170.9             235.1             107.9   
50                          163.2              86.0              87.4   

    Rates.Race.Indigenous  Rates.Race and Sex.Female.White  \
35                   55.5                            157.9   
36                  194.2                            159.0   
37                  138.7                            151.0   
38                   56.7                            151.7   
39                  142.5                            149.7   
40                  102.2                            144.0   
41                  226.5                            139.7   
42                   62.0                            153.7   
43                   36.2                            136.2   
44                  114.5                            109.9   
45                    0.0                            151.4   
46                   68.6                            144.5   
47                  167.8                            149.4   
48                   75.1                            167.1   
49                  214.0                            145.1   
50                  177.4                            142.4   

    Rates.Race and Sex.Female.White non-Hispanic  \
35                                         158.6   
36                                         160.8   
37                                         152.6   
38                                         152.3   
39                                         151.9   
40                                         144.5   
41                                         140.0   
42                                         154.9   
43                                         145.4   
44                                         110.5   
45                                         151.3   
46                                         145.9   
47                                         151.3   
48                                         167.9   
49                       

In [38]:
df.loc[35:, 'Rates.Age and Sex.> 64.Male':'Rates.Race and Sex.Male.White']

Rates.Age and Sex.> 64.Male  Rates.Race.White  \
35                       1288.3             185.3   
36                       1279.4             190.2   
37                       1169.2             173.7   
38                       1276.5             177.7   
39                       1291.3             176.7   
40                       1195.1             175.1   
41                       1195.0             163.3   
42                       1294.7             189.4   
43                       1104.0             162.5   
44                        884.9             128.9   
45                       1165.8             175.0   
46                       1170.7             168.9   
47                       1142.0             171.3   
48                       1299.9             198.6   
49                       1233.6             169.9   
50                       1064.5             161.5   

    Rates.Race.White non-Hispanic  Rates.Race.Black  Rates.Race.Asian  \
35                          186.0             218.0              98.7   
36                          192.6             222.1             122.1   
37                          175.5             200.8             118.0   
38                          178.2             222.4              96.5   
39                          179.0             128.6             113.2   
40                          176.1             211.2              88.1   
41                          163.8              77.4             149.0   
42                          190.9             231.6              93.5   
43                          172.6             208.6              94.4   
44                          129.7             132.0             105.3   
45                          175.0             130.3             109.2   
46                          170.7             208.0              98.8   
47                          173.5             189.0             120.1   
48                          199.4             216.3              67.1   
49                          170.9             235.1             107.9   
50                          163.2              86.0              87.4   

    Rates.Race.Indigenous  Rates.Race and Sex.Female.White  \
35                   55.5                            157.9   
36                  194.2                            159.0   
37                  138.7                            151.0   
38                   56.7                            151.7   
39                  142.5                            149.7   
40                  102.2                            144.0   
41                  226.5                            139.7   
42                   62.0                            153.7   
43                   36.2                            136.2   
44                  114.5                            109.9   
45                    0.0                            151.4   
46                   68.6                            144.5   
47                  167.8                            149.4   
48                   75.1                            167.1   
49                  214.0                            145.1   
50                  177.4                            142.4   

    Rates.Race and Sex.Female.White non-Hispanic  \
35                                         158.6   
36                                         160.8   
37                                         152.6   
38                                         152.3   
39                                         151.9   
40                                         144.5   
41                                         140.0   
42                                         154.9   
43                                         145.4   
44                                         110.5   
45                                         151.3   
46                                         145.9   
47                                         151.3   
48                                         167.9   
49                       

<div style="background-color:#f3e5f5; color:black; padding:20px; border-radius:15px; border: 1px solid #ccc; box-shadow: 0 2px 4px rgba(0,0,0,0.1);">
  <h2 style="margin-top: 0;">Exercises 12</h2>
print unique values of the Rates.Age.< 18 column!
</div>

In [42]:
df['Rates.Age.< 18'].unique()

array([2. , 1.7, 2.5, 2.3, 2.6, 1.9, 1.6, 2.2, 0. , 2.1, 2.4, 2.7, 1.4])

<div style="background-color:#f3e5f5; color:black; padding:20px; border-radius:15px; border: 1px solid #ccc; box-shadow: 0 2px 4px rgba(0,0,0,0.1);">
  <h2 style="margin-top: 0;">Exercises 13</h2>
print mean of the Rates.Age.< 18
</div>

In [43]:
df['Rates.Age.< 18'].mean()

2.119607843137255

<div style="background-color:#f3e5f5; color:black; padding:20px; border-radius:15px; border: 1px solid #ccc; box-shadow: 0 2px 4px rgba(0,0,0,0.1);">
  <h2 style="margin-top: 0;">Exercises 14</h2>
Find max of Total.Population and subtract all values of Total.Population column from the maximum value using lambda function.
</div>

In [45]:
max_val = df["Total.Population"].max()

In [46]:
df["Total.Population"].map(lambda x: max_val - x)

0     227748491.0
1     256169516.0
2     216290098.0
3     240753248.0
4             0.0
5     225867962.0
6     236159807.0
7     254840433.0
8     256890337.0
9     128858625.0
10    193245044.0
11    251609613.0
12    250181401.0
13    171438735.0
14    215763006.0
15    239813614.0
16    241206913.0
17    230787639.0
18    229497310.0
19    251834514.0
20    220651717.0
21    215243424.0
22    191747123.0
23    223951967.0
24    240378824.0
25    219297306.0
26    254202673.0
27    248350172.0
28    242223389.0
29    251912307.0
30    199614141.0
31    246785934.0
32    125419172.0
33    194466627.0
34    256380793.0
35    180394453.0
36    234906552.0
37    234303580.0
38    172310014.0
39    253764060.0
40    228769562.0
41    255421389.0
42    216704860.0
43     84865275.0
44    241814234.0
45    256758434.0
46    205081363.0
47    214021456.0
48    248195484.0
49    221346797.0
50    257204072.0
Name: Total.Population, dtype: float64

<div style="background-color:#f3e5f5; color:black; padding:20px; border-radius:15px; border: 1px solid #ccc; box-shadow: 0 2px 4px rgba(0,0,0,0.1);">
  <h2 style="margin-top: 0;">Exercises 15</h2>
    <p style="font-size:16px;"><b>Class and Object</b></p><br>
Class and Object
Implement following architecture using OOP!
use __str__ to print output same as: Breed of the dog is {Breed}, It is {Size} and {Color} , the dog is {Age} years old.
</div>

In [47]:
class Dog:
    def __init__(self, name, breed, size, age, color):
        self.name = name
        self.breed = breed
        self.size = size
        self.age = age
        self.color = color
    
    def eat(self):
        return f"{self.name} is eating."
    
    
    def sleep(self):
        return f"{self.name} is sleaping."
    
    def sit(self):
        return f"{self.name} is sitting."
    
    def run(self):
        return f"{self.name} is running."
    
    def __str__(self):
        return f"Breed of the dog is {self.breed}, It is {self.size} and {self.color} , the dog is {self.age} years old."

In [49]:
#Ex
B = Dog(name='Bella', breed='X', size='Medume', age=3, color='brown')

In [50]:
str(B)

'Breed of the dog is X, It is Medume and brown , the dog is 3 years old.'

## Finished!